@startuml
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour terminerJeu
participant ":JeuDeDes" as c
participant "joueurs:\nMap<String, Joueur>" as jm
->c : redemarrerJeu()
note right : selon Contrôleur \n(JeuDeDés est \nl'objet racine)
c->jm : clear()
note right : selon Expert
@enduml
